import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar"; // must have "use client" at top

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Keep body static; no dynamic classes */}
      <body className="antialiased">
        {/* Navbar is client component */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
